# ---------------------------------------------------------------------------
# Free Mount Settings
# ---------------------------------------------------------------------------
# Related skills: data/stats/skills/custom/mount_skills.xml

# Enable free strider mount.
# Default: False
EnableFreeStrider = True

# Enable free wyvern mount.
# Default: False
EnableFreeWyvern = True
